### ISSUE TITLE
Question regarding authorizations.

### ISSUE THREAD

**Issue by scharada** [mgernand/AspNetCore.Endpoints#7]
Hi. nice library. i had a question though. where can the permissions from the permissions library can be used with the endpoints here ?
is there a sample to look at ?

**Comment by scharada** [comment]
never mind. was too quick asking ...

**Comment by mgernand** [comment]
Hi! 
I will add extension methods for using the permissions policy with Minimal API. There will be an extension like this: 

```app.MapGet(/*...*/).RequirePermission("Invoices.Read");```

Look out for the next release.
